#!/bin/bash

ACTION="$1"
shift
PACKAGE_LIST="$@"

# Epic-gtk bug !!! Doesn't support echoes out of predefined sections
if [ "x$ACTION" != "xgetStatus" ];then
	echo "ACTION=$ACTION PKG_LIST=$PACKAGE_LIST"
fi
case $ACTION in
	getStatus)
		# status=$(dpkg-query -W -f '${Status}' "$PACKAGE_LIST" 2>/dev/null)
		# if [ "$status" == "install ok installed" ];then
		# 	echo 0
		# else
		# 	echo 1
		# fi
		echo "Not found"
	;;
	preInstall)
		echo "preInstall..."
		statusA=$(egrep -A1 '"zero-lliurex-smart"' /var/lib/n4d/variables-dir/ZEROCENTER|grep state|sed -nr 's/.*"state": ([^,]+),/\1/p')
		statusB=$(dpkg-query -W -f '${Status}' lliurex-smart 2>/dev/null)
		statusC=$(dpkg-query -W -f '${Status}' nwfermi-module 2>/dev/null)
		ret=0
		if [ "${statusA}" == "1" ]; then
			kdialog --error "Unable to install, this installer is incompatible with unofficial smart installer!\nPlease remove all packages from unofficial installer first"
			ret=1
		fi
		if [ "${statusB}" == 'install ok installed' ]; then
			kdialog --error "Unable to install, this installer is incompatible with lliurex-smart from unofficial smart installer!\nPlease remove lliurex-smart from unofficial installer first"
			ret=1
		fi
		if [ "${statusC}" == 'install ok installed' ]; then
			kdialog --error "Unable to install, this installer is incompatible with nwfermi-module from unofficial smart installer!\nPlease remove nwfermi-module from unofficial installer first"
			ret=1
		fi
		#bionic need additional repository
		codename=$(lsb_release -sc)
		if [ "${codename}" == "bionic" ];then
			add-apt-repository -y -u ppa:m-angel-juan/nbdeps
			status=$(dpkg-query -W -f'${Status}' fakelib-notebook 2>/dev/null)
			if [ "${status}" != "install ok installed" ];then
				apt-get install -y fakelib-notebook
			fi
		fi
		exit $ret
	;;
	installPackage)
		echo "installPackage..."
	;;
	postInstall)
		echo "postInstall..."
	;;
	remove)
		echo "remove..."
		pkgs="fwupdatesmart smart-languagesetup smart-gallerysetup smart-notebook smart-product-drivers smart-activation smart-common smart-hwr nwfermi-module-host"
		uninstall=""
		for pkg in $pkgs; do 
			status=$(dpkg-query -W -f'${Status}' ${pkg} 2>/dev/null)
			if [ "${status}" == "install ok installed" ];then
				uninstall="$uninstall $pkg"
			fi
		done
		if [ -n "$uninstall" ];then
			apt-get remove -y $uninstall
		fi
		codename=$(lsb_release -sc)
		if [ "${codename}" == "bionic" ];then
			add-apt-repository -y -u -r ppa:m-angel-juan/nbdeps
			status=$(dpkg-query -W -f'${Status}' fakelib-notebook 2>/dev/null)
			if [ "${status}" == "install ok installed" ];then
				apt-get remove -y fakelib-notebook
			fi
		fi
	;;
esac
exit 0

