#!/bin/bash

ACTION="$1"
shift
PACKAGE_LIST="$@"

# Epic-gtk bug !!! Doesn't support echoes out of predefined sections
if [ "x$ACTION" != "xgetStatus" ];then
	echo "ACTION=$ACTION PKG_LIST=$PACKAGE_LIST"
fi
case $ACTION in
	getStatus)
		# status=$(dpkg-query -W -f '${Status}' "$PACKAGE_LIST" 2>/dev/null)
		# if [ "$status" == "install ok installed" ];then
		# 	echo 0
		# else
		# 	echo 1
		# fi
		echo "Not found"
	;;
	preInstall)
		echo "preInstall..."
		kdialog --error "Preinstall"
		#status=$(egrep -A1 '"zero-lliurex-smart"' /var/lib/n4d/variables-dir/ZEROCENTER|grep state|sed -nr 's/.*"state": ([^,]+),/\1/p')
		#status=$(dpkg-query -W -f '${Status}' lliurex-smart 2>/dev/null)

		exit 1
	;;
	installPackage)
		echo "installPackage..."
	;;
	postInstall)
		echo "postInstall..."
	;;
	remove)
		echo "remove..."
	;;
esac
exit 0

