#!/bin/bash



ACTION="$1"

case $ACTION in

	postInstall)

		docker pull lliurex/lliurex-smart

		check_download=$(docker images lliurex/lliurex-smart -q)
		

		if [ "$check_download" == " " ]; then
			exit 1
		fi

esac
exit 0

